import ExactSemiprimes.Definitions

/-!
# Construction of the sparse polynomial `P₁(s)^k / k!`

This file isolates the finite combinatorics in the definition of the paper's
sparse Dirichlet polynomial.  If `S` is a finite set of primes, an ordered
`k`-tuple from `S` contributes to the coefficient at the product of its
entries.  The coefficient is the size of this fibre divided by `k!`.

Unique factorisation says that every two tuples in a fibre are reorderings of
one another.  Consequently the fibre has at most `k!` elements, even when a
prime is repeated, and every coefficient belongs to `[0,1]`.
-/

namespace ExactSemiprimes
namespace Sparse

open scoped BigOperators

noncomputable section

/-- An ordered `k`-tuple with entries in the finite set `S`. -/
abbrev PrimeTuple (S : Finset ℕ) (k : ℕ) := Fin k → S

/-- The product attached to an ordered tuple. -/
def primeTupleProduct {S : Finset ℕ} {k : ℕ} (f : PrimeTuple S k) : ℕ :=
  ∏ i, (f i : ℕ)

/-- Ordered tuples from `S` whose product is `n`. -/
def primeTupleFiber (S : Finset ℕ) (k n : ℕ) : Finset (PrimeTuple S k) :=
  Finset.univ.filter fun f ↦ primeTupleProduct f = n

/-- The number of ordered `k`-tuples from `S` with product `n`. -/
def primeTupleCount (S : Finset ℕ) (k n : ℕ) : ℕ :=
  (primeTupleFiber S k n).card

/-- The finite multiplicative support generated by exactly `k` factors from
`S`.  For `k = 0` this is the singleton `{1}`. -/
def primePowerSupport (S : Finset ℕ) (k : ℕ) : Finset ℕ :=
  Finset.univ.image fun f : PrimeTuple S k ↦ primeTupleProduct f

/-- The real coefficient of `n` in the normalized `k`th power. -/
def primePowerCoefficient (S : Finset ℕ) (k n : ℕ) : ℝ :=
  (primeTupleCount S k n : ℝ) / (Nat.factorial k : ℝ)

/-- The finite prime Dirichlet polynomial `P₁(s)` associated with `S`. -/
def primeBasePolynomial (S : Finset ℕ) (s : ℂ) : ℂ :=
  ∑ p ∈ S, (p : ℂ) ^ (-s)

/-- The normalized power `P₁(s)^k / k!` used in the sparse-polynomial
argument. -/
def primePowerPolynomial (S : Finset ℕ) (k : ℕ) (s : ℂ) : ℂ :=
  primeBasePolynomial S s ^ k / (Nat.factorial k : ℂ)

/-- On natural-number indices, complex exponentiation by a fixed exponent is
multiplicative.  This packages `Complex.natCast_mul_natCast_cpow` in the form
needed to evaluate a tuple product. -/
def natCpowMonoidHom (s : ℂ) : ℕ →* ℂ where
  toFun n := (n : ℂ) ^ s
  map_one' := by simp
  map_mul' m n := by
    simpa only [Nat.cast_mul] using Complex.natCast_mul_natCast_cpow m n s

@[simp]
theorem natCpowMonoidHom_apply (s : ℂ) (n : ℕ) :
    natCpowMonoidHom s n = (n : ℂ) ^ s := rfl

theorem primeTupleProduct_cpow {S : Finset ℕ} {k : ℕ}
    (f : PrimeTuple S k) (s : ℂ) :
    (primeTupleProduct f : ℂ) ^ s = ∏ i, ((f i : ℕ) : ℂ) ^ s := by
  change natCpowMonoidHom s (∏ i, (f i : ℕ)) =
    ∏ i, natCpowMonoidHom s (f i : ℕ)
  exact map_prod (natCpowMonoidHom s) (fun i ↦ (f i : ℕ)) Finset.univ

/-- Expanding the `k`th power produces the sum over ordered prime tuples. -/
theorem primePowerPolynomial_eq_tupleSum (S : Finset ℕ) (k : ℕ) (s : ℂ) :
    primePowerPolynomial S k s =
      (∑ f : PrimeTuple S k, (primeTupleProduct f : ℂ) ^ (-s)) /
        (Nat.factorial k : ℂ) := by
  rw [primePowerPolynomial, primeBasePolynomial]
  have hbase :
      (∑ p ∈ S, (p : ℂ) ^ (-s)) =
        ∑ p : S, ((p : ℕ) : ℂ) ^ (-s) := by
    exact Finset.sum_subtype S (by simp) fun p ↦ (p : ℂ) ^ (-s)
  rw [hbase, Fintype.sum_pow]
  congr 1
  apply Finset.sum_congr rfl
  intro f _
  exact (primeTupleProduct_cpow f (-s)).symm

/-- Grouping the tuple expansion according to the product of a tuple gives
the expected coefficient multiplicity. -/
theorem primeTupleSum_eq_coefficientSum (S : Finset ℕ) (k : ℕ) (s : ℂ) :
    (∑ f : PrimeTuple S k, (primeTupleProduct f : ℂ) ^ (-s)) =
      ∑ n ∈ primePowerSupport S k,
        (primeTupleCount S k n : ℂ) * (n : ℂ) ^ (-s) := by
  have hmaps : ∀ f ∈ (Finset.univ : Finset (PrimeTuple S k)),
      primeTupleProduct f ∈ primePowerSupport S k := by
    intro f _
    simp [primePowerSupport]
  have hgroup := Finset.sum_fiberwise_of_maps_to hmaps
    (fun f : PrimeTuple S k ↦ (primeTupleProduct f : ℂ) ^ (-s))
  have hinter (n : ℕ) :
      (∑ f ∈ (Finset.univ : Finset (PrimeTuple S k)) with
          primeTupleProduct f = n, (primeTupleProduct f : ℂ) ^ (-s)) =
        (primeTupleCount S k n : ℂ) * (n : ℂ) ^ (-s) := by
    change (∑ f ∈ primeTupleFiber S k n,
      (primeTupleProduct f : ℂ) ^ (-s)) = _
    calc
      _ = ∑ _f ∈ primeTupleFiber S k n, (n : ℂ) ^ (-s) := by
        apply Finset.sum_congr rfl
        intro f hf
        rw [show primeTupleProduct f = n by
          simpa [primeTupleFiber] using hf]
      _ = (primeTupleCount S k n : ℂ) * (n : ℂ) ^ (-s) := by
        simp [primeTupleCount]
  calc
    _ = ∑ n ∈ primePowerSupport S k,
        ∑ f ∈ (Finset.univ : Finset (PrimeTuple S k)) with
          primeTupleProduct f = n, (primeTupleProduct f : ℂ) ^ (-s) := hgroup.symm
    _ = _ := by
      apply Finset.sum_congr rfl
      intro n _
      exact hinter n

/-- The normalized power is a finite Dirichlet polynomial on
`primePowerSupport`, with the fibre-count coefficients defined above. -/
theorem primePowerPolynomial_eq_supportSum (S : Finset ℕ) (k : ℕ) (s : ℂ) :
    primePowerPolynomial S k s =
      ∑ n ∈ primePowerSupport S k,
        (primePowerCoefficient S k n : ℂ) * (n : ℂ) ^ (-s) := by
  rw [primePowerPolynomial_eq_tupleSum,
    primeTupleSum_eq_coefficientSum, Finset.sum_div]
  apply Finset.sum_congr rfl
  intro n _
  simp only [primePowerCoefficient, Complex.ofReal_div,
    Complex.ofReal_natCast]
  ring

@[simp]
theorem mem_primeTupleFiber {S : Finset ℕ} {k n : ℕ} {f : PrimeTuple S k} :
    f ∈ primeTupleFiber S k n ↔ primeTupleProduct f = n := by
  simp [primeTupleFiber]

@[simp]
theorem mem_primePowerSupport {S : Finset ℕ} {k n : ℕ} :
    n ∈ primePowerSupport S k ↔
      ∃ f : PrimeTuple S k, primeTupleProduct f = n := by
  simp [primePowerSupport]

theorem primeTupleCount_eq_zero_of_not_mem {S : Finset ℕ} {k n : ℕ}
    (hn : n ∉ primePowerSupport S k) :
    primeTupleCount S k n = 0 := by
  rw [primeTupleCount, Finset.card_eq_zero]
  apply Finset.not_nonempty_iff_eq_empty.mp
  rintro ⟨f, hf⟩
  exact hn (mem_primePowerSupport.mpr ⟨f, mem_primeTupleFiber.mp hf⟩)

theorem primePowerCoefficient_eq_zero_of_not_mem {S : Finset ℕ} {k n : ℕ}
    (hn : n ∉ primePowerSupport S k) :
    primePowerCoefficient S k n = 0 := by
  simp [primePowerCoefficient, primeTupleCount_eq_zero_of_not_mem hn]

/-- The list underlying a tuple.  Naming this map makes the use of unique
factorisation in the cardinality argument transparent. -/
def primeTupleList {S : Finset ℕ} {k : ℕ} (f : PrimeTuple S k) : List ℕ :=
  List.ofFn fun i ↦ (f i : ℕ)

theorem primeTupleList_injective {S : Finset ℕ} {k : ℕ} :
    Function.Injective (primeTupleList : PrimeTuple S k → List ℕ) := by
  intro f g h
  apply funext
  intro i
  apply Subtype.ext
  exact congrFun (List.ofFn_injective h) i

@[simp]
theorem primeTupleList_length {S : Finset ℕ} {k : ℕ} (f : PrimeTuple S k) :
    (primeTupleList f).length = k := by
  simp [primeTupleList]

@[simp]
theorem primeTupleList_prod {S : Finset ℕ} {k : ℕ} (f : PrimeTuple S k) :
    (primeTupleList f).prod = primeTupleProduct f := by
  simp [primeTupleList, primeTupleProduct, List.prod_ofFn]

theorem primeTupleList_all_prime {S : Finset ℕ} {k : ℕ}
    (hS : ∀ p ∈ S, Nat.Prime p) (f : PrimeTuple S k) :
    ∀ p ∈ primeTupleList f, Nat.Prime p := by
  intro p hp
  simp only [primeTupleList, List.mem_ofFn] at hp
  obtain ⟨i, rfl⟩ := hp
  exact hS (f i) (f i).property

/-- The precise combinatorial core: a product of `k` primes has at most `k!`
ordered representations using a prescribed finite prime set. -/
theorem primeTupleFiber_card_le_factorial {S : Finset ℕ} {k n : ℕ}
    (hS : ∀ p ∈ S, Nat.Prime p) :
    (primeTupleFiber S k n).card ≤ Nat.factorial k := by
  let lists : Finset (List ℕ) :=
    (primeTupleFiber S k n).image primeTupleList
  have hcard : (primeTupleFiber S k n).card = lists.card := by
    symm
    exact Finset.card_image_of_injective _ primeTupleList_injective
  by_cases hfiber : (primeTupleFiber S k n).Nonempty
  · obtain ⟨f₀, hf₀⟩ := hfiber
    have hperm₀ : (primeTupleList f₀).Perm n.primeFactorsList := by
      apply Nat.primeFactorsList_unique
      · simpa using mem_primeTupleFiber.mp hf₀
      · exact primeTupleList_all_prime hS f₀
    have hlength : n.primeFactorsList.length = k := by
      simpa using hperm₀.length_eq.symm
    have hsubset : lists ⊆ n.primeFactorsList.permutations.toFinset := by
      intro l hl
      rcases Finset.mem_image.mp hl with ⟨f, hf, rfl⟩
      rw [List.mem_toFinset, List.mem_permutations]
      apply Nat.primeFactorsList_unique
      · simpa using mem_primeTupleFiber.mp hf
      · exact primeTupleList_all_prime hS f
    calc
      (primeTupleFiber S k n).card = lists.card := hcard
      _ ≤ n.primeFactorsList.permutations.toFinset.card :=
        Finset.card_le_card hsubset
      _ ≤ n.primeFactorsList.permutations.length := List.toFinset_card_le _
      _ = Nat.factorial n.primeFactorsList.length := List.length_permutations _
      _ = Nat.factorial k := by rw [hlength]
  · rw [Finset.not_nonempty_iff_eq_empty.mp hfiber, Finset.card_empty]
    exact Nat.zero_le _

theorem primeTupleCount_le_factorial {S : Finset ℕ} {k n : ℕ}
    (hS : ∀ p ∈ S, Nat.Prime p) :
    primeTupleCount S k n ≤ Nat.factorial k := by
  exact primeTupleFiber_card_le_factorial hS

theorem primePowerCoefficient_nonneg (S : Finset ℕ) (k n : ℕ) :
    0 ≤ primePowerCoefficient S k n := by
  exact div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)

theorem primePowerCoefficient_le_one {S : Finset ℕ} {k n : ℕ}
    (hS : ∀ p ∈ S, Nat.Prime p) :
    primePowerCoefficient S k n ≤ 1 := by
  rw [primePowerCoefficient, div_le_one (by positivity : (0 : ℝ) < Nat.factorial k)]
  exact_mod_cast primeTupleCount_le_factorial hS

/-- Every coefficient of the normalized prime power lies in the closed unit
interval. -/
theorem primePowerCoefficient_mem_unitInterval {S : Finset ℕ} {k n : ℕ}
    (hS : ∀ p ∈ S, Nat.Prime p) :
    primePowerCoefficient S k n ∈ Set.Icc (0 : ℝ) 1 := by
  exact ⟨primePowerCoefficient_nonneg S k n,
    primePowerCoefficient_le_one hS⟩

/-- In particular, the coefficient bound applies directly to the dyadic prime
set used in the paper. -/
theorem dyadic_primePowerCoefficient_mem_unitInterval (P : ℝ) (k n : ℕ) :
    primePowerCoefficient (dyadicPrimes P) k n ∈ Set.Icc (0 : ℝ) 1 := by
  apply primePowerCoefficient_mem_unitInterval
  intro p hp
  exact (Finset.mem_filter.mp hp).2

def primePowerPolynomialModule : ProofModule :=
  { name := "Sparse.PrimePowerPolynomial"
    paperLocation := "Section 6.1, definition of Q(s)"
    purpose := "Define the sparse support and prove that its coefficients lie in [0,1]."
    dependsOn := ["Definitions", "Mathlib's fundamental theorem of arithmetic"]
    status := .proved }

end

end Sparse
end ExactSemiprimes
